version: '3'
services:
  master:
    environment: 
      - "LOCUST_HOST=${LOCUST_HOST}"
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H https://www.exness-trade.pro --headless -u 1000  -r 100 --run-time 5s --csv=$LOCUST_HOST 

  worker:
    deploy:
      replicas: 4
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master --csv=$LOCUST_HOST 
