version: '3'
services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: "-f /mnt/locust/locustfile.py -H $HOST --master --headless -u 1000  -r 100 --run-time 5s --html=/mnt/locust/$DOMAIN.html"

  worker:
    deploy:
      replicas: 4
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: "-f /mnt/locust/locustfile.py --worker --master-host master "
