version: '3'
services:
  master:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: "-f /mnt/locust/locustfile.py -H https://${DOMAIN} --master --headless -u 1000  -r 100 --run-time 5s --html=/mnt/locust/$DOMAIN.html"

  worker:
    deploy:
      replicas: $WORKERS
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: "-f /mnt/locust/locustfile.py --worker --master-host master "
